### ISSUE TITLE
Add 2-way sync with Shopping list

### ISSUE THREAD

**Issue by weeebdev** [Anrolosia/Shopping-List-with-Grocy#59]
I'd love to have this feature! Right now I guess shopping list can be modified only from grocy itself, and not from HA. Also, my Voice Assistant already manages default shopping list, and I'd love to sync it with it

**Comment by KonstBr** [comment]
I'm adding my problem because I want something similar

I would like to fill the shopping list with assist. I have two problems.

I tell the assistant the name of the item. But your integration adds based on the ID and not the name. 

How do I deal with articles that have not yet been set up and do not have an ID?

**Comment by KonstBr** [comment]
I have a solution

```
alias: Grocy Einkaufsliste
description: ""
triggers:
  - trigger: conversation
    command:
      - Füge {artikel} zur einkaufsliste (zu|hinzu)
      - (Ich|Wir) (brauche|brauchen) [neue|neuen] {artikel}
conditions: []
actions:
  - action: rest_command.grocy_get_items
    metadata: {}
    data: {}
    response_variable: grocy_response
  - variables:
      product_name: "{{ trigger.slots.artikel}}"
      product: |
        {% if grocy_response %}
         {% set products = grocy_response['content'] %}
         {{ products | selectattr('name', 'equalto', product_name) | first }}
        {% endif %}
  - if:
      - condition: template
        value_template: |
          {{ product == '' }}
    then:
      - action: rest_command.grocy_post_item
        data:
          name: "{{ trigger.slots.artikel}} "
          location: 1
          qu_id_purchase: 3
          qu_id_stock: 3
        response_variable: NewProductID
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - action: shopping_list_with_grocy.refresh_products
        metadata: {}
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - action: shopping_list_with_grocy.add_product
        metadata: {}
        data:
          product_id: >-
            sensor.shopping_list_with_grocy_product_v2_{{NewProductID.content.created_object_id}}
        enabled: true
      - set_conversation_response: >-
          okay, ich habe {{states['sensor.shopping_list_with_grocy_product_v2_'
          + NewProductID.content.created_object_id | string].name}} auf die
          Einkaufsliste geschrieben
    enabled: true
    else:
      - action: shopping_list_with_grocy.add_product
        metadata: {}
        data:
          product_id: sensor.shopping_list_with_grocy_product_v2_{{product.id}}
        enabled: true
      - set_conversation_response: >-
          okay, ich habe {{states['sensor.shopping_list_with_grocy_product_v2_'
          + product.id | string].name}} auf die Einkaufsliste geschrieben
mode: single
```
